### PR TITLE
Added Timer listner to get notified when timer reaches zero

### PR DESCRIPTION
**Pull request by stormtheh4ck3r**

### CODE REVIEW

**Comment by stormtheh4ck3r** [comment]
please check and merge this

**Comment by alexfu** [comment]
Apologies for the delay :+1:

**Comment by stormtheh4ck3r** [comment]
Thank you

**Comment by stormtheh4ck3r** [comment]
how did u add your library to android-arsenal.com?

**Comment by alexfu** [comment]
@stormtheh4ck3r i didn't add it. whoever maintains that site must of added it.

**Comment by stormtheh4ck3r** [comment]
ok can i re-implement this in android studio?

**Pull request merged**
